/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:492be0b1-c3ce-4145-a96a-7c8fd555ee13",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bpmTSQpJi",
    "aws_user_pools_web_client_id": "5f6acnf9c7uncs4l8i23i2798j",
    "oauth": {}
};


export default awsmobile;
